HocWeb/HocWeb/Controllers/ChiTietController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HocWeb.Models;
using Models.Framwork;
using Models.Dao;
using Models.ViewModel;

namespace HocWeb.Controllers
{
    public class ChiTietController : Controller
    {
        DoAnWEB db = new DoAnWEB();
        // GET: ChiTiet
        public ActionResult ChiTiet()
        {
            return View();
        }
        public ViewResult XemChiTiet(int productID=0)
        {
            Product sanpham = db.Products.SingleOrDefault(n => n.ID == productID);
            if(sanpham==null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sanpham);
        }
        public PartialViewResult HienChiTietSanPhamPartial(int proID)
        {
            var SanPham = db.Products.Single(n => n.ID == proID);
            return PartialView(SanPham);
        }
        public PartialViewResult Relative(int cateID)
        {
            var sanpham= db.Products.Where(n => n.CategoryID == cateID).ToList();
            return PartialView(sanpham);
        }
        public PartialViewResult RelativeBrand(int brandID)
        {
            var sanpham = db.Products.Where(n => n.BrandID == brandID).Take(5).ToList();
            return PartialView(sanpham);
        }
        public PartialViewResult SalesPartial()
        {
            var SPKM = db.Products.Take(3).ToList();
            return PartialView(SPKM);
        }
        public JsonResult ListName(string q)
        {
            var data = new ProductDao().ListName(q);
            return Json(new
            {
                data = data,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Search(string keyword, int page = 1, int pageSize = 1)
        {
            int totalRecord = 0;
            var model = new ProductDao();
            var model2 = new List<ProductViewModel>();
            model2 = model.Search(keyword, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            ViewBag.Keyword = keyword;
            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model2);
        }
        //bài viết tin tức
        public ViewResult XemChiTiet_tintuc(int contentID = 0)
        {
            Content baiviet = db.Contents.SingleOrDefault(n => n.ID == contentID);
            if (baiviet == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(baiviet);
        }
        public PartialViewResult ChiTietTinTucPartial(int proID)
        {
            var Tin = db.Contents.Single(n => n.ID == proID);
            return PartialView(Tin);
        }
        public PartialViewResult RelativeTinTucPartial()
        {
            var content = db.Contents.ToList();
            return PartialView(content);
        }
        [HttpPost]
        public ActionResult Send_FB(string name, string mobile, string address, string email, string content)
        {
            var feedback = new Feedback();
            feedback.Name = name;
            feedback.Email = email;
            feedback.CreatedDate = DateTime.Now;
            feedback.Phone = mobile;
            feedback.Content = content;
            feedback.Address = address;
            feedback.Status = true;
            var id = new ContactDao().InsertFeedBack(feedback);
            return Redirect("/hoan-thanh");
        }
    }
}

HocWeb/HocWeb/Controllers/ThongTinShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HocWeb.Models;
using PagedList;
using Commom;
using System.Configuration;
using HocWeb.Areas.Admin.Code;
using Models.Framwork;
using Models.Dao;
using System.Web.Script.Serialization;
using Models.ViewModel;

namespace HocWeb.Controllers
{
    public class ThongTinShopController : Controller
    {
        // GET: ThongTinShop
        public ActionResult MuaTraGop()
        {
            return View();
        }
        public ActionResult Index()
        {
            var model = new ContactDao().GetActiveContact();
            return View(model);
        }

        [HttpPost]
        public JsonResult Send(string name, string mobile, string address, string email, string content)
        {
            var feedback = new Feedback();
            feedback.Name = name;
            feedback.Email = email;
            feedback.CreatedDate = DateTime.Now;
            feedback.Phone = mobile;
            feedback.Content = content;
            feedback.Address = address;
            feedback.Status = true;
            var id = new ContactDao().InsertFeedBack(feedback);
            string content1 = System.IO.File.ReadAllText(Server.MapPath("~/Assets/client/vendor/SentFeedBack.html"));
            content1 = content1.Replace("{{Name}}", name);
            content1 = content1.Replace("{{Address}}", address);
            content1 = content1.Replace("{{Email}}", email);
            content1 = content1.Replace("{{Detail}}", content);

            var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();
            try
            {
                new MailHelper().SentMail(toEmail, "Thông tin Feed back", content1);
                new MailHelper().SentMail(feedback.Email, "Thông tin Feed back", content1);
            }
            catch { }
          
            if (id > 0)
            {
              
                return Json(new
                {
                    status = true,
                   

            });
                //sent
                
            }
            else
            {
                return Json(new
                {
                    status = false
                });
            }

        }

     
    }
}

HocWeb/HocWeb/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HocWeb.Models;
using HocWeb.Areas.Admin.Controllers;
using Models.Framwork;
using HocWeb.Areas.Admin.Code;
using Models.Dao;
using PagedList;

namespace HocWeb.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: TrangChu
        DoAnWEB db = new DoAnWEB();
        List<Product> listpro = new List<Product>();
        public ActionResult Index()
        {
           
            return View();
        }
        public PartialViewResult NewSanPhamPartial()
        {
            var SanPham = db.Products.OrderBy(n=>n.CreatedDate).ToList();
            return PartialView(SanPham);
        }
        public ActionResult NewSanPham(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            List<Product> Lstsanpham = db.Products.Take(15).OrderBy(n => n.CreatedDate).ToList();

            if (Lstsanpham.Count == 0)
            {
                ViewBag.Product = "Không có sản phẩm nào";
                return null;
            }
            if (Lstsanpham.Count < pageSize)
                pageSize = Lstsanpham.Count;
            return View(Lstsanpham.ToPagedList(pageNumber, pageSize));
        }
        public PartialViewResult DienThoaiPartial()
        {
            var SanPham = db.Products.Where(n => n.CategoryID == 1).Take(3).ToList();
            return PartialView(SanPham);
        }
        public PartialViewResult DoanhMucPartial()
        {
            var DoanhMuc= db.ProductCategories.ToList();
            return PartialView(DoanhMuc);
        }

        public PartialViewResult SanPhamKhuyenMaiPartial()
        {
            var SPKM = db.Products.Where(x=>x.Price!=x.PromotionPrice).Take(5).ToList();
            return PartialView(SPKM);
        }
        public List<Product> SanPham(int proCate)
        {
            return db.Products.Where(n => n.CategoryID == proCate).OrderBy(n => n.Price).ToList();
        }
        public ViewResult DoanhMucSP(int? page,int proCate=0)
        {
            
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            ProductCategory procate = db.ProductCategories.SingleOrDefault(n => n.ID == proCate);
            if(procate==null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<Product> Lstsanpham = db.Products.Where(n => n.CategoryID == proCate).OrderBy(n => n.Price).ToList();

            if (Lstsanpham.Count==0)
            {
                ViewBag.Product = "Không có sản phẩm nào";
                return null;
            }
            if (Lstsanpham.Count< pageSize)
                pageSize = Lstsanpham.Count;
            return View(Lstsanpham.ToPagedList(pageNumber, pageSize));
        }
        public ViewResult SanPhamTheoHang(int? page, int brandID = 0)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            Brand procate = db.Brands.SingleOrDefault(n => n.ID == brandID);
            if (procate == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<Product> Lstsanpham = db.Products.Where(n => n.BrandID == brandID).OrderBy(n => n.Price).ToList();

            if (Lstsanpham.Count == 0)
            {
                ViewBag.Product = "Không có sản phẩm nào";
                return null;
            }
            if (Lstsanpham.Count < pageSize)
                pageSize = Lstsanpham.Count;
            return View(Lstsanpham.ToPagedList(pageNumber, pageSize));
        }
        public PartialViewResult LaptopPartial()
        {
            var lap = db.Products.Where(n => n.CategoryID == 41).Take(3).ToList();
            return PartialView(lap);
        }
        public PartialViewResult PhuKienPartial()
        {
            var phukien= db.Products.Where(n => n.CategoryID == 43).Take(3).ToList();
            return PartialView(phukien);
        }
        public PartialViewResult TabletPartial()
        {
            var tablet = db.Products.Where(n => n.CategoryID == 2).Take(3).ToList();
            return PartialView(tablet);
        }
        public PartialViewResult Slider()
        {
            var slider = db.Contents.Take(5).ToList();
            return PartialView(slider);
        }
        public PartialViewResult HangPartial()
        {
            var hang = db.ProductCategories.Take(6).ToList();
            return PartialView(hang);
        }
        [HttpGet]
        public ActionResult InfoUser()
        {
            var session = (UserSession)Session[CommomConstants.USER_SESSION];          
            var result = new UserDao().ViewDetail(session.UserID);
            return View(result);
        }
      
        [HttpPost]
        public ActionResult InfoUser(User user)
        {
            if (ModelState.IsValid)
            {
                var session = (UserSession)Session[CommomConstants.USER_SESSION];
                var dao = new UserDao();
                if (!string.IsNullOrEmpty(user.Passwords))
                {
                    var encrytedMd5 = Encryptor.MD5Hash(user.Passwords);
                    user.Passwords = encrytedMd5;
                    user.ModifiedBy = session.TenTK;
                    user.ModifiedDate = DateTime.Now;
                    user.Position = session.ChucVu;
                }
                 dao.UpdateDetail(user);              
            }
            return View(user);
        }
        public ActionResult Logout()
        {
            Session[CommomConstants.USER_SESSION] = null;
            return View("index");
        }
        public ActionResult LoiPhanQuyen()
        {            
            return View();
        }
        public ViewResult ReturnProduct()
        {
            return View();
        }
        public ViewResult FreeShip()
        {
            return View();
        }
        public ViewResult SecurePayment()
        {
            return View();
        }
    }
}

HocWeb/HocWeb/Views/Layout/Cart_Layout1.cshtml
@using HocWeb.Areas.Admin.Code
@{
    var session = (UserSession)Session[CommomConstants.USER_SESSION];
}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cart Page - Ustora Demo</title>

    <link rel="stylesheet" href="~/Assets/client/css/u_css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Assets/client/css/u_css/font-awesome.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/Assets/client/css/u_css/owl.carousel.css">
    <link rel="stylesheet" href="~/Assets/client/style.css">
    <link rel="stylesheet" href="~/Assets/client/css/u_css/responsive.css">
    <!-- Google Fonts -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>

    <!-- Bootstrap -->
    <!--Jquery-->>
    <script src="~/Assets/client/js/U_js/jquery-1.12.4.js"></script>
    <script src="~/Assets/client/js/U_js/jquery-ui.js"></script>
    <script src="https://code.jquery.com/jquery.min.js"></script>
    <!-- Bootstrap JS form CDN -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <!-- jQuery sticky menu -->
    <script src="~/Assets/client/js/U_js/owl.carousel.min.js"></script>
    <script src="~/Assets/client/js/U_js/jquery.easing.1.3.min.js"></script>
    <script src="~/Assets/client/js/U_js/jquery.sticky.js"></script>
    <script src="~/Assets/client/js/U_js/main.js"></script>
</head>
<body>

    <div class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="user-menu">
                        <ul>
                            @if (session != null)
                            {
                                <li><a href="/TrangChu/InfoUser"><i class="fa fa-user"></i>Chào mừng @session.Name</a></li>
                                <img class="img-circle" src="@session.Avartar" width="30" height="30">
                                <li><a href="/TrangChu/Logout"><i class="fa fa-user"></i>Đăng xuất</a></li>
                            }
                            else
                            {
                                <li><a href="/Admin/Login/Index"><i class="fa fa-user"></i>Đăng nhập</a></li>
                            }

                            <li><a href="/GioHang/Index"><i class="fa fa-user"></i>Xem giỏ hàng</a></li>


                        </ul>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="user-menu">
                        <ul>
                            @if (session != null)
                            {
                                if (session.ChucVu == "2" || session.ChucVu == "3")
                                {

                                    <li><a href="/admin/default/index"><i class="fa fa-user"></i>ADMIN</a></li>
                                    <li><a href="/trangchu/index"><i class="fa fa-user"></i>HOME</a></li>

                                }
                                else
                                {
                                    <li><a href="/trangchu/index"><i class="fa fa-user"></i>HOME</a></li>
                                }

                            }
                            else
                            {
                                <li><a href="/trangchu/index"><i class="fa fa-user"></i>HOME</a></li>
                            }



                            <li><a href="@Url.Action("Index","ThongTinShop")"><i class="fa fa-user"></i>About</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End header area -->
    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="logo">
                        <h1>
                            <a href="@Url.Action("Index", "TrangChu")">
                                <img src="~/Assets/client/images/icons/new icon/icon.png" width="45" height="40" />DATA
                            </a>
                            <br>THE BEST SHOP
                        </h1>
                    </div>
                </div>

                @Html.Action("HeaderCart", "GioHang")
            </div>
        </div>
    </div> <!-- End site branding area -->

    <div class="mainmenu-area">
        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @Html.Action("DoanhMucPartial", "TrangChu")
                    </ul>
                </div>
            </div>
        </div>
    </div> <!-- End mainmenu area -->

    <div class="product-big-title-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="product-bit-title text-center">
                        <h2>Shopping Cart</h2>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End Page title area -->


    <div class="single-product-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="single-sidebar">
                        <h2 class="sidebar-title">Search Products</h2>
                        <form action="/tim-kiem" method="get">
                            <input id="txtKeyword" type="text" name="keyword" placeholder="Search products...">
                            <input type="submit" value="Search">
                        </form>
                    </div>

                    @Html.Action("SalesPartial", "ChiTiet")

                </div>

                <div class="col-md-8">
                    <div class="product-content-right">
                        <div class="woocommerce">
                            <form method="post" action="#">
                                @RenderBody()
                                @*<table cellspacing="0" class="shop_table cart">
                                        <thead>
                                            <tr>
                                                <th class="product-remove">&nbsp;</th>
                                                <th class="product-thumbnail">&nbsp;</th>
                                                <th class="product-name">San phẩm</th>
                                                <th class="product-price">Giá</th>
                                                <th class="product-quantity">Số lượng</th>
                                                <th class="product-subtotal">Tổng</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            <tr>
                                                <td class="actions" colspan="6">

                                                    <input type="submit" value="Xóa" name="update_cart" class="button">
                                                    <input type="submit" value="Thanh Toán" name="proceed" class="checkout-button button alt wc-forward">
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>*@

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="footer-top-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="footer-about-us">
                        <h2><span>ADATA SHOP</span></h2>
                        <ul>
                            <li><a href="/TrangChu/Index">Tìm hiểu về mua trả góp</a></li>
                            <li><a href="/TrangChu/Index">Chính sách bảo hành</a></li>
                            <li><a href="/TrangChu/Index">Chính sách đổi trả</a></li>
                            <li><a href="/TrangChu/Index">Giao hàng & thanh toán</a></li>
                            <li><a href="/TrangChu/Index">In hóa đơn điện tử</a></li>
                            <li><a href="/TrangChu/Index">Chất lượng phục vụ</a></li>
                            <li><a href="/TrangChu/Index">Chính sách khui hộp sản phẩm của Apple</a></li>
                        </ul>

                    </div>
                </div>

                @if (session != null)
                {
                    <div class="col-md-3 col-sm-6">
                        <div class="footer-menu">
                            <h2 class="footer-wid-title">Thông tin người dùng</h2>
                            <ul>
                                <li><a href="/TrangChu/InfoUser">@session.Name</a></li>
                                <li><a href="/TrangChu/Index">Order history</a></li>
                                <li><a href="/TrangChu/Index">Wishlist</a></li>
                                <li><a href="/TrangChu/Index">Vendor contact</a></li>
                                <li><a href="/TrangChu/Index">Front page</a></li>
                            </ul>
                        </div>
                    </div>
                }
                else
                {
                    <div class="col-md-3 col-sm-6">
                        <div class="footer-menu">
                            <h2 class="footer-wid-title">Thông tin người dùng</h2>
                            <ul>
                                <li><a href="/admin/login/index">My account</a></li>
                                <li><a href="/TrangChu/Index">Order history</a></li>
                                <li><a href="/TrangChu/Index">Wishlist</a></li>
                                <li><a href="/TrangChu/Index">Vendor contact</a></li>
                                <li><a href="/TrangChu/Index">Front page</a></li>
                            </ul>
                        </div>
                    </div>
                }


                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Hỗ trợ khác hàng</h2>
                        <ul>
                            <li><p>Gọi mua hàng</p><a href="/TrangChu/Index">  1800.1060 (7:30 - 22:00)</a></li>
                            <li><p>Gọi khiếu nại</p><a href="/TrangChu/Index"> 1800.1060 (7:30 - 22:00)</a></li>
                            <li><p>Gọi bảo hành</p><a href="/TrangChu/Index">  1800.1060 (7:30 - 22:00)</a></li>
                            <li><p>Kỹ thuật</p><a href="/TrangChu/Index">      1800.1060 (7:30 - 22:00)</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-newsletter">
                        <h2 class="footer-wid-title">Bản tin</h2>
                        <p>Đăng kí tài khoản ngay để nhận các ưu đãi giảm giá mới nhất</p>
                        <div class="newsletter-form">
                            <ul>
                                <li><a href="/admin/register/register">Đăng kí ngay</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer top area -->

    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="copyright">
                        <p>&copy; @DateTime.Now.Year ADATA SHOP .THE BEST PHONE SHOP</p>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer bottom area -->
    <!-- Latest jQuery form server -->
    <!-- Latest jQuery form server -->
    @*<cript src="https://code.jquery.com/jquery.min.js"></script>*@

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Bootstrap JS form CDN -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <!-- jQuery sticky menu -->
    <script src="~/Assets/client/js/U_js/owl.carousel.min.js"></script>
    <script src="~/Assets/client/js/U_js/jquery.sticky.js"></script>

    <!-- jQuery easing -->
    <script src="~/Assets/client/js/U_js/jquery.easing.1.3.min.js"></script>

    <!-- Main Script -->
    <script src="~/Assets/client/js/U_js/main.js"></script>
    @RenderSection("jsFooter", required: false)
</body>
</html>

HocWeb/HocWeb/Views/Layout/FindLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FindLayout</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>