HocWeb/HocWeb/Areas/Admin/Controllers/CateProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using HocWeb.Areas.Admin.Models;
using HocWeb.Areas.Admin.Code;
using Models.Framwork;
using Models.Dao;
using System.Web;
using System.Web.Mvc;


namespace HocWeb.Areas.Admin.Controllers
{
    public class CateProductController : BaseController
    {
        // GET: Admin/CateProduct
        public ActionResult Index(int page = 1, int pageSize = 1000, string searchString = null)
        {
            var dao = new CateProductDao();
            var model = dao.ListAllPaging(page, pageSize, searchString);
            ViewBag.SearchString = searchString;
            return View(model);
        }
        [HttpGet]
        public ActionResult Edit(long ID)
        {
            var category = new CateProductDao().ViewDetail(ID);
            return View(category);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public JsonResult ChangeStatus(long id)
        {
            var result = new CateProductDao().ChangeStatus(id);
            return Json(new
            {
                status = result
            });
        }
        [HttpPost]
        public JsonResult ChangeShowOnHome(long id)
        {
            var result = new CateProductDao().ChangeShowOnHome(id);
            return Json(new
            {
                ShowOnHome = result
            });
        }
        [HttpPost]
        public ActionResult Create(ProductCategory model)
        {
            var dao = new CateProductDao();
            var result = dao.CheckProduct(model.Name);
          
            if (ModelState.IsValid)
            {
                if(result==false)
                {
                    var session = (UserSession)Session[CommomConstants.USER_SESSION];
                    model.CreatedDate = DateTime.Now;
                    model.ModifiedDate = DateTime.Now;
                    model.ModifiedBy = session.TenTK;
                    model.CreatedBy = session.TenTK;
                    var id = new CateProductDao().Insert(model);
                    if (id > 0)
                    {
                        SetAlert("Thêm danh mục thành công", "success");
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        SetAlert("Thêm danh mục thất bại", "error");
                    }
                }             
                else
                {
                    SetAlert("Tên danh mục đã tồn tại", "error");
                }
               
                
            }
            return View(model);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(ProductCategory category)
        {
            if (ModelState.IsValid)
            {
                var session = (UserSession)Session[CommomConstants.USER_SESSION];

                var dao = new CateProductDao();
                category.ModifiedDate = DateTime.Now;
                category.ModifiedBy = session.TenTK;
                var result = dao.update(category);
                if (result)
                {
                     SetAlert("Sửa danh mục sản phẩm thành công", "success");
                    return RedirectToAction("Index");
                }
                else
                {
                    SetAlert("Sửa danh mục không thành công", "error");
                }
            }
            return View(category);
        }
        public ActionResult Detail(long id)
        {
            var result = new CateProductDao().ViewDetail(id);
            return View(result);
        }
    }
}

HocWeb/HocWeb/Areas/Admin/Views/CateProduct/Create.cshtml
@model Models.Framwork.ProductCategory
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutView.cshtml";
}

@section header{

}

@using (Html.BeginForm("Create", "CateProduct", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="container-fluid">
        <h1 class="m-0 font-weight-bold text-primary">Thêm mới danh mục sản phẩm</h1>
        <div>
            <a  class="btn btn-primary" href="/Admin/Category/Index" style="width:100px;" > Trở về </a>
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            <div class="col-sm-3 mb-1 mb-sm-0">
                <p>Tên danh mục</p>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control form-control-user", @autofocus = "autofocus" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <div class="col-sm-3">
                <p>Tiêu đề danh mục</p>
                @Html.EditorFor(model => model.MetaTitle, new { htmlAttributes = new { @class = "form-control form-control-user" } })
                @Html.ValidationMessageFor(model => model.MetaTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-1 mb-sm-0">
                <p>MetaDescriptions</p>
                @Html.EditorFor(model => model.MetaDescriptions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MetaDescriptions, "", new { @class = "text-danger" })
            </div>
           
        </div>

        <div class="form-group row">
            <div class="col-sm-3 mb-1 mb-sm-0">
                <p>MetaKeywords</p>
                @Html.EditorFor(model => model.MetaKeywords, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MetaKeywords, "", new { @class = "text-danger" })
            </div>
            <div class="col-sm-3">
                <p>DisplayOrder</p>
                @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })
               
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-3 mb-1 mb-sm-0">
                <p>Status</p>
                @Html.DropDownListFor(model => model.Status, new[] { new SelectListItem { Text = "Hoạt động", Value = "True" }, new SelectListItem { Text = "Khóa", Value = "False" } }, new { @class = "form-control form-control-user" })
            </div>
            <div class="col-sm-3">
                <p>ShowOnHome</p>
                @Html.DropDownListFor(model => model.ShowOnHome, new[] { new SelectListItem { Text = "Show", Value = "True" }, new SelectListItem { Text = "None", Value = "False" } }, new { @class = "form-control form-control-user" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" style="width:100px;" />
            </div>
        </div>
    </div>
}
<script src="~/Assets/Admin/vendor/jquery/jquery.min.js"></script>
<script src="~/Assets/Admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="~/Assets/Admin/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="~/Assets/Admin/js/sb-admin-2.min.js"></script>

HocWeb/HocWeb/Areas/Admin/Views/CateProduct/Detail.cshtml
@model Models.Framwork.ProductCategory

@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutView.cshtml";
}

@section header{

}

<div class="container-fluid">
    <h1 class="m-0 font-weight-bold text-primary">Chi tiết danh mục sản phẩm</h1>
    <hr />
    <div class="form-group row">
        <div class="col-sm-3 mb-1 mb-sm-0">
            <dl class="dl-horizontal" style="font-size: 24px">
               
                <dt>
                    Tên danh mục
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    Tiêu đề danh mục
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.MetaTitle)
                </dd>

                <dt>
                    Thứ tự xuất hiện
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DisplayOrder)
                </dd>
                <dt>
                    Keywords
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.MetaKeywords)
                </dd>

                <dt>
                    Mô tả
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.MetaDescriptions)
                </dd>
            </dl>
        </div>
        <div class="col-sm-3">
            <dl class="dl-horizontal" style="font-size: 24px">
                <dt>
                    Ngày tạo danh mục
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CreatedDate)
                </dd>

                <dt>
                    Tài khoản tạo danh mục
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CreatedBy)
                </dd>

                <dt>
                    Ngày sửa danh mục
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ModifiedDate)
                </dd>

                <dt>
                    Tài khoản sửa danh mục
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ModifiedBy)
                </dd>
                <dt>
                    Trạng thái
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Status)
                </dd>

                <dt>
                    Hiển thị
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ShowOnHome)
                </dd>
            </dl>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <a href="/admin/cateproduct/index" class="btn btn-primary" style="width:100px;">Trở về</a>
    </div>
</div>

HocWeb/HocWeb/Areas/Admin/Views/CateProduct/Edit.cshtml
@model Models.Framwork.ProductCategory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutView.cshtml";
}

@section header{

}

@using (Html.BeginForm("Edit", "CateProduct", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="container-fluid">
        <h1 class="m-0 font-weight-bold text-primary">Thêm mới danh mục sản phẩm</h1>
        <div>
            <a class="btn btn-primary" href="/Admin/Category/Index"> Trở về </a>
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group row">
            <div class="col-sm-3 mb-1 mb-sm-0">
                <p>Tên danh mục</p>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control form-control-user", @autofocus = "autofocus" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <div class="col-sm-3">
                <p>Tiêu đề danh mục</p>
                @Html.EditorFor(model => model.MetaTitle, new { htmlAttributes = new { @class = "form-control form-control-user" } })
                @Html.ValidationMessageFor(model => model.MetaTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-1 mb-sm-0">
                <p>MetaDescriptions</p>
                @Html.EditorFor(model => model.MetaDescriptions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MetaDescriptions, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group row">
            <div class="col-sm-3 mb-1 mb-sm-0">
                <p>MetaKeywords</p>
                @Html.EditorFor(model => model.MetaKeywords, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MetaKeywords, "", new { @class = "text-danger" })
            </div>
            <div class="col-sm-3">
                <p>DisplayOrder</p>
                @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-3 mb-1 mb-sm-0">
                <p>Status</p>
                @Html.DropDownListFor(model => model.Status, new[] { new SelectListItem { Text = "Hoạt động", Value = "True" }, new SelectListItem { Text = "Khóa", Value = "False" } }, new { @class = "form-control form-control-user" })
            </div>
            <div class="col-sm-3">
                <p>ShowOnHome</p>
                @Html.DropDownListFor(model => model.ShowOnHome, new[] { new SelectListItem { Text = "Show", Value = "True" }, new SelectListItem { Text = "None", Value = "False" } }, new { @class = "form-control form-control-user" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" style="width:100px;" />
            </div>
        </div>
    </div>
}

HocWeb/HocWeb/Areas/Admin/Views/CateProduct/Index.cshtml
@model PagedList.IPagedList<Models.Framwork.ProductCategory>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutView.cshtml";
}
@section header{

}
@section jsFooter{

    <script src="~/Assets/Admin/js/controller/CategoryController.js"></script>
}
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="m-0 font-weight-bold text-primary">Danh sách danh mục sản phẩm</h1>
    <div>
        <a  class="btn btn-primary" href="/Admin/CateProduct/Create"> Thêm mới </a>
    </div>
    <hr />
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>

                                <th>Name</th>
                                <th>MetaTitle</th>
                                <th>Descriptions</th>
                                <th>Status</th>
                                <th>ShowOnHome</th>
                                <th>#</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>

                                <th>Name</th>
                                <th>MetaTitle</th>
                                <th>Descriptions</th>
                                <th>Status</th>
                                <th>ShowOnHome</th>
                                <th>#</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr id="row_@item.ID">
                                <td>@item.Name</td>
                                <td>@item.MetaTitle</td>
                                <td>@item.MetaDescriptions</td>
                                <td><a href="#" class="btn-active" data-id="@item.ID">@(item.Status ? "Đang hoạt động" : "Đang khóa")</a></td>
                                <td><a href="#" class="btn-active1" data-id="@item.ID">@(item.ShowOnHome ? "Show" : "None")</td>
                                <td>
                                    <a class="btn btn-success" href="/Admin/CateProduct/Edit/@item.ID">Edit</a>
                                    <a class="btn btn-primary" href="/Admin/CateProduct/Detail/@item.ID">Details</a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>